# Generated by Django 5.2.5 on 2025-11-12 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(help_text='Introductory text for the signup page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text="Adresse de l'utilisateur", max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text="Code postal de l'utilisateur", max_length=16)),
                ('phone_number', models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=20)),
                ('country', models.ForeignKey(blank=True, help_text="Pays de l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.country')),
                ('user', models.OneToOneField(help_text="L'utilisateur associé à ce profil", on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
