# Generated by Django 5.2.5 on 2025-11-19 07:56

import app.animals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('breed', models.CharField(blank=True, max_length=150, verbose_name='Race')),
                ('category', models.CharField(choices=[('dog', 'Chien'), ('cat', 'Chat')], default='dog', max_length=10)),
                ('age_years', models.PositiveIntegerField(default=0, validators=[app.animals.models.validate_positive])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[app.animals.models.validate_positive])),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('U', 'Inconnu')], default='U', max_length=1)),
                ('vet_name', models.CharField(blank=True, max_length=150, verbose_name='Nom du vétérinaire')),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur / Propriétaire')),
                ('photo', models.ForeignKey(blank=True, help_text="Photo de l'animal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'animals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='animals_ani_owner_i_a0c9aa_idx'), models.Index(fields=['category'], name='animals_ani_categor_165793_idx')],
            },
        ),
    ]
