# Generated by Django 5.2.5 on 2025-11-20 11:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sidebar Menu', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SidebarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('menu_name', models.CharField(max_length=255)),
                ('url_name', models.CharField(help_text="Nom de l'URL Django", max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text="Classe CSS pour l'icône", max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('coming_soon', 'Bientôt')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboards.sidebarmenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
