# Generated by Django 5.2.5 on 2025-11-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='intro',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='introduction',
        ),
    ]
