# Generated by Django 5.2.6 on 2025-11-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_wishlistpage'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('large_title', models.CharField(help_text='Main title for the page', max_length=255)),
                ('subtitle', models.CharField(help_text='A subtitle or secondary title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description or content for the page')),
                ('image', models.ForeignKey(blank=True, help_text='A small image to represent the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
