# Generated by Django 5.2.6 on 2025-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_slider_slide_homepage_slider_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
