# Generated by Django 5.2.6 on 2025-11-07 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_slider_title'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Identifier the section of the page where this slider will appear (e.g. header, testimonials)', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_placements', to='wagtailcore.page')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='base.slider')),
            ],
        ),
    ]
