# Generated by Django 5.2.6 on 2025-11-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_sliderplacement'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderplacement',
            options={'verbose_name': 'Slider Placement', 'verbose_name_plural': 'Slider Placements'},
        ),
        migrations.AlterField(
            model_name='sliderplacement',
            name='page',
            field=models.ForeignKey(help_text='Page sur laquelle ce slider sera affiché.', on_delete=django.db.models.deletion.CASCADE, related_name='slider_placements', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='sliderplacement',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('testimonials', 'Testimonials'), ('gallery', 'Gallery'), ('footer', 'Footer')], help_text='Section où afficher ce slider (ex: header, testimonials...).', max_length=50),
        ),
        migrations.AlterField(
            model_name='sliderplacement',
            name='slider',
            field=models.ForeignKey(help_text='Le slider à afficher sur cette page.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='base.slider'),
        ),
    ]
