# Generated by Django 5.2.5 on 2025-11-14 19:50

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfessionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Confession Category",
                "verbose_name_plural": "Confession Categories",
            },
        ),
        migrations.CreateModel(
            name="ConfessionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Confession Tag",
                "verbose_name_plural": "Confession Tags",
            },
        ),
        migrations.CreateModel(
            name="ConfessionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introduction text for the confession page",
                    ),
                ),
                (
                    "is_public_feed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this page shows public confessions",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filter confessions by category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="confession.confessioncategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Confession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pseudo",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated pseudonym for anonymous content",
                        max_length=100,
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Main text content of the confession"),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("ironique", "Ironique"),
                            ("rage", "Rage"),
                            ("desabuse", "Désabusé"),
                            ("triste", "Triste"),
                            ("neutre", "Neutre"),
                            ("joyeux", "Joyeux"),
                            ("courageux", "Courageux"),
                        ],
                        default="neutre",
                        help_text="Tone classification for content (ironique, rage, desabusé, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Boolean indicating if displayed on public feed",
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean indicating company-targeted content",
                    ),
                ),
                (
                    "sarcasm_score",
                    models.FloatField(
                        blank=True,
                        help_text="Float computed by AI for sarcasm detection",
                        null=True,
                    ),
                ),
                (
                    "generated_title",
                    models.CharField(
                        blank=True,
                        help_text="AI-generated title string",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable ForeignKey to User (null for anonymous confessions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable ForeignKey to Wagtail Image for AI-generated images",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="confession.confessioncategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="confession.confessiontag"),
                ),
            ],
            options={
                "verbose_name": "Confession",
                "verbose_name_plural": "Confessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
